/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Member {
  id?: number;
  name?: string;
  email?: string;
  password?: string;
  role?: string;
  phone: string;
}
