/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Member
} from './model';

import { memberFetcher } from '../fetcher';
export const getAll = (
    
 signal?: AbortSignal
) => {
      
      
      return memberFetcher<Member[]>(
      {url: `/api/member`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllQueryKey = () => {
    return [`/api/member`] as const;
    }

    
export const getGetAllQueryOptions = <TData = Awaited<ReturnType<typeof getAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({ signal }) => getAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>
export type GetAllQueryError = unknown


export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postCreateMember = (
    member: Member,
 signal?: AbortSignal
) => {
      
      
      return memberFetcher<Member>(
      {url: `/api/member`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      body: member, signal
    },
      );
    }
  


export const getPostCreateMemberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCreateMember>>, TError,{data: Member}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postCreateMember>>, TError,{data: Member}, TContext> => {

const mutationKey = ['postCreateMember'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCreateMember>>, {data: Member}> = (props) => {
          const {data} = props ?? {};

          return  postCreateMember(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostCreateMemberMutationResult = NonNullable<Awaited<ReturnType<typeof postCreateMember>>>
    export type PostCreateMemberMutationBody = Member
    export type PostCreateMemberMutationError = unknown

    export const usePostCreateMember = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCreateMember>>, TError,{data: Member}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCreateMember>>,
        TError,
        {data: Member},
        TContext
      > => {

      const mutationOptions = getPostCreateMemberMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
export const updateByPhone = (
    phone: string,
 signal?: AbortSignal
) => {
      
      
      return memberFetcher<string>(
      {url: `/api/member/update/${phone}`, method: 'POST', signal
    },
      );
    }
  


export const getUpdateByPhoneMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateByPhone>>, TError,{phone: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateByPhone>>, TError,{phone: string}, TContext> => {

const mutationKey = ['updateByPhone'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateByPhone>>, {phone: string}> = (props) => {
          const {phone} = props ?? {};

          return  updateByPhone(phone,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateByPhoneMutationResult = NonNullable<Awaited<ReturnType<typeof updateByPhone>>>
    
    export type UpdateByPhoneMutationError = unknown

    export const useUpdateByPhone = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateByPhone>>, TError,{phone: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateByPhone>>,
        TError,
        {phone: string},
        TContext
      > => {

      const mutationOptions = getUpdateByPhoneMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
export const findByEmail = (
    email: string,
 signal?: AbortSignal
) => {
      
      
      return memberFetcher<string>(
      {url: `/api/member/${email}`, method: 'GET', signal
    },
      );
    }
  

export const getFindByEmailQueryKey = (email: string,) => {
    return [`/api/member/${email}`] as const;
    }

    
export const getFindByEmailQueryOptions = <TData = Awaited<ReturnType<typeof findByEmail>>, TError = unknown>(email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByEmail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindByEmailQueryKey(email);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findByEmail>>> = ({ signal }) => findByEmail(email, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(email), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findByEmail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindByEmailQueryResult = NonNullable<Awaited<ReturnType<typeof findByEmail>>>
export type FindByEmailQueryError = unknown


export function useFindByEmail<TData = Awaited<ReturnType<typeof findByEmail>>, TError = unknown>(
 email: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByEmail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByEmail>>,
          TError,
          Awaited<ReturnType<typeof findByEmail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByEmail<TData = Awaited<ReturnType<typeof findByEmail>>, TError = unknown>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByEmail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByEmail>>,
          TError,
          Awaited<ReturnType<typeof findByEmail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByEmail<TData = Awaited<ReturnType<typeof findByEmail>>, TError = unknown>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByEmail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindByEmail<TData = Awaited<ReturnType<typeof findByEmail>>, TError = unknown>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByEmail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindByEmailQueryOptions(email,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const hello = (
    
 signal?: AbortSignal
) => {
      
      
      return memberFetcher<string>(
      {url: `/api/member/hello`, method: 'GET', signal
    },
      );
    }
  

export const getHelloQueryKey = () => {
    return [`/api/member/hello`] as const;
    }

    
export const getHelloQueryOptions = <TData = Awaited<ReturnType<typeof hello>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof hello>>> = ({ signal }) => hello(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HelloQueryResult = NonNullable<Awaited<ReturnType<typeof hello>>>
export type HelloQueryError = unknown


export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello>>,
          TError,
          Awaited<ReturnType<typeof hello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof hello>>,
          TError,
          Awaited<ReturnType<typeof hello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHelloQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteByPhone = (
    phone: string,
 ) => {
      
      
      return memberFetcher<string>(
      {url: `/api/member/delete/${phone}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteByPhoneMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteByPhone>>, TError,{phone: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteByPhone>>, TError,{phone: string}, TContext> => {

const mutationKey = ['deleteByPhone'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteByPhone>>, {phone: string}> = (props) => {
          const {phone} = props ?? {};

          return  deleteByPhone(phone,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteByPhoneMutationResult = NonNullable<Awaited<ReturnType<typeof deleteByPhone>>>
    
    export type DeleteByPhoneMutationError = unknown

    export const useDeleteByPhone = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteByPhone>>, TError,{phone: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteByPhone>>,
        TError,
        {phone: string},
        TContext
      > => {

      const mutationOptions = getDeleteByPhoneMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
